FROM alpine AS base

RUN apk update

RUN apk add curl bash unzip

RUN apk add python3 py3-pip

RUN apk add py3-urllib3

COPY get_resources.sh get_resources.sh

RUN ./get_resources.sh

FROM python:3.12-slim-bullseye

COPY --from=base /resources /resources

COPY requirements ./requirements

RUN pip install -r ./requirements/test.txt

COPY service /service

COPY tests /tests

COPY pytest.ini pytest.ini

CMD [ "pytest" ]
